// 'use client';

import { Outfit } from "next/font/google";
import { FC } from "react";

import type { Metadata } from "next";

import "@/styles/globals.css";

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Abdul Wahab | Senior Ui/UX Designer",
  description: "Generated by create next app",
};

type TProps = Readonly<IChildren>;
const RootLayout: FC<TProps> = ({ children }) => (
  <html lang="en">
    <body className={`${outfit.variable} antialiased`}>{children}</body>
  </html>
);

export default RootLayout;
